---
- - :permit
  - MIT
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 01:55:51.429439100 Z
- - :permit
  - ISC
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:00:10.960824500 Z
- - :permit
  - BSD
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:00:48.608694400 Z
- - :permit
  - Python Software Foundation License
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:01:14.298710000 Z
- - :permit
  - Simplified BSD
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:01:28.972522900 Z
- - :permit
  - Apache 2.0
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:01:42.801093000 Z
- - :permit
  - CC0-1.0
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:01:57.707287400 Z
- - :permit
  - MIT/X11
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:02:08.599410600 Z
- - :permit
  - New BSD
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:02:20.566269000 Z
- - :permit
  - Expat license
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:04:52.898901000 Z
- - :permit
  - ASL
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:06:33.891629700 Z
- - :permit
  - Mozilla Public License 2.0
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:06:56.556790400 Z
- - :permit
  - LGPL
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:15:55.862389300 Z
- - :permit
  - Apache License v2.0
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:16:05.679307500 Z
- - :permit
  - Public Domain
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:16:14.403847400 Z
- - :permit
  - GNU LGPL
  - :who:
    :why:
    :versions: []
    :when: 2019-11-19 02:16:20.654080000 Z
- - :approve
  - docutils
  - :who:
    :why: Using public domain part of this
    :versions: []
    :when: 2019-11-22 01:45:34.996197115 Z
- - :approve
  - idna
  - :who:
    :why: Modified BSD, checked and valid
    :versions: []
    :when: 2019-11-22 01:45:53.040643508 Z
- - :approve
  - python-dateutil
  - :who:
    :why: BSD and Apache2 licensed
    :versions: []
    :when: 2019-11-22 01:46:11.170672095 Z
